totem {
    version: 2
    cluster_name: hana_diskless_sbd
}
nodelist {
    node {
        ring0_addr: vmh3shdb03
        nodeid: 1
    }
    node {
        ring0_addr: vmh3shdb01
        nodeid: 2
    }
    node {
        ring0_addr: vmh3shdb02
        nodeid: 3
    }
}
quorum {
    provider: corosync_votequorum
}
