totem {
    version: 2
    cluster_name: hana_cluster_2
}
nodelist {
    node {
        ring0_addr: vmhdbqas01
        nodeid: 1
    }
    node {
        ring0_addr: vmhdbqas02
        nodeid: 2
    }
}
quorum {
    provider: corosync_votequorum
}
