totem {
    version: 2
    cluster_name: hana_scale_out_cluster
}
nodelist {
    node {
        ring0_addr: vms4prdhdb01
        nodeid: 1
    }
    node {
        ring0_addr: vms4prdhdb02
        nodeid: 2
    }
    node {
        ring0_addr: vms4prdhdb03
        nodeid: 3
    }
    node {
        ring0_addr: vms4prdhdb04
        nodeid: 4
    }
    node {
        ring0_addr: vms4prdmm
        nodeid: 5
    }
}
quorum {
    provider: corosync_votequorum
}
