totem {
    version: 2
    cluster_name: hana_cost_opt
}
nodelist {
    node {
        ring0_addr: vmhdbcost01
        nodeid: 1
    }
    node {
        ring0_addr: vmhdbcost02
        nodeid: 2
    }
}
quorum {
    provider: corosync_votequorum
}
